services:
  metabase:
    build: .
    container_name: metabase-automotive
    ports:
      - "3000:3000"
    environment:
      - JAVA_TIMEZONE=America/Sao_Paulo
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/tmp/metabase/metabase
    restart: unless-stopped
